[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix backend --no-audit"
]

[phases.build]
cmds = [
  "npm run build --prefix backend",
  "npm prune --omit=dev --no-audit --prefix backend"
]

[start]
cmd = "cd backend && node dist/server.js"
