
import pool from '../src/config/database';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../.env') });

const removeTriggerAndFixNotifications = async () => {
    try {
        console.log('Connecting to database...');
        const client = await pool.connect();

        try {
            console.log('Dropping mention notification trigger...');
            await client.query('DROP TRIGGER IF EXISTS trigger_mention_notification ON mentions');
            await client.query('DROP FUNCTION IF EXISTS notify_user_mention');
            console.log('Trigger dropped successfully.');

            console.log('Removing duplicate English notifications...');
            // Remove notifications that look like the English ones generated by the trigger
            // pattern: Title contains "mentioned you in"
            const deleteResult = await client.query(
                `DELETE FROM notifications 
         WHERE type = 'mention' 
         AND title LIKE '% mentioned you in %'`
            );
            console.log(`Deleted ${deleteResult.rowCount} duplicate notifications.`);

        } finally {
            client.release();
        }

        console.log('Done.');
        process.exit(0);
    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
};

removeTriggerAndFixNotifications();
